# Generated by Django 4.1.6 on 2023-02-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(max_length=80)),
                ('birth_date', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('attending_doctor', models.CharField(max_length=80)),
                ('app_type', models.CharField(max_length=80)),
            ],
        ),
    ]
