# Generated by Django 4.1.6 on 2023-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverDia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diausers',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='diausers',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='diausers',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
