# Generated by Django 4.1.6 on 2023-02-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverDia', '0002_alter_diausers_birth_date_alter_diausers_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diausers',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diausers',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diausers',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
