# Generated by Django 4.1.6 on 2023-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverDia', '0003_alter_diausers_birth_date_alter_diausers_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diausers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
