# Generated by Django 4.1.6 on 2023-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverDia', '0004_diausers_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diausers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
