# Generated by Django 4.1.6 on 2023-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverDia', '0005_alter_diausers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diausers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
